create database SQL_Assignment2;

SELECT * FROM PETOWNERS LIMIT 5;
SELECT * FROM PETS LIMIT 5;
SELECT * FROM PROCEDURESDETAILS LIMIT 5;
SELECT * FROM PROCEDURESHISTORY LIMIT 5;

-- 1. List the names of all pet owners along with the names of their pets. 

SELECT PETOWNERS.NAME AS OWENER_NAME, PETS.NAME AS PET_NAME FROM PETOWNERS JOIN PETS ON PETOWNERS.OWNERID = PETS.OWNERID;

-- 2. List all pets and their owner names, including pets that don't have recorded owners.

SELECT PETOWNERS.NAME AS OWENER_NAME, PETS.NAME AS PET_NAME FROM PETS LEFT JOIN PETOWNERS ON PETOWNERS.OWNERID = PETS.OWNERID; 

-- 3. Combine the information of pets and their owners, including those pets without owners and owners without pets. 

SELECT PETOWNERS.NAME AS OWENER_NAME, PETS.NAME AS PET_NAME FROM PETS LEFT JOIN PETOWNERS ON PETOWNERS.OWNERID = PETS.OWNERID UNION SELECT PETOWNERS.NAME AS OWENER_NAME, PETS.NAME AS PET_NAME FROM PETS RIGHT JOIN PETOWNERS ON PETOWNERS.OWNERID = PETS.OWNERID;

-- 4. List all pet owners and the number of dogs they own.

SELECT PETOWNERS.NAME AS OWENER_NAME, COUNT(PETS.PETID) AS NUMBER_OF_PETS FROM PETOWNERS LEFT JOIN PETS ON PETOWNERS.OWNERID = PETS.OWNERID GROUP BY PETOWNERS.OWNERID , PETOWNERS.NAME;

-- 5. Identify pets that have not had any procedures.

SELECT PETS.NAME AS PET_NAME FROM PETS JOIN PROCEDURESHISTORY ON PETS.PETID = PROCEDURESHISTORY.PETID;

-- Find the name of the oldest pet.

SELECT NAME , AGE FROM PETS ORDER BY AGE DESC LIMIT 1;

-- 7. Find the details of procedures performed on 'Cuddles'.






