SELECT FIRSTNAME , LASTNAME , SALARY , AVG(SALARY) 
OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC ) AS AVGDEAPARTMENTSALARY
FROM EMPLOYEES;

SELECT EMPLOYEEID , FIRSTNAME , LASTNAME , SALARY , LEAD(SALARY,1)
OVER (ORDER BY SALARY DESC) AS NEXTHHIGHESTSALARY 
FROM EMPLOYEES;